### ISSUE TITLE
Migrations not running

### ISSUE THREAD

**Issue by robinheghan** [giggio/FluentMigrator.Runner.DNX#18]
I've just tried this and it doesn't work. The project compiles just fine, but it doesn't seem that the migrations are actually being run. --verbose outputs nothing.

I've tried both `dotnet migrate --provider mysql --noConnection --outputFile test.sql` and `dotnet migrate --provider mysql --connectionString [string]`

I've followed the instructions in the top-level README.md, and used the migration in test/ as a sample migration.

**Comment by eloekset** [comment]
My first guess is that the problem has the same cause as this issue just recently opened in the main repo: https://github.com/schambers/fluentmigrator/issues/734 

If your assembly containing migrations is compiled against another version of FluentMigrator than the FluentMigrator.Runner assembly, the runner won't recognize the MigrationAttribute and won't find any migration steps in your assembly.

**Comment by robinheghan** [comment]
Hmm. I'm just using the version that Runner.CLI depends on. What version should I pull in instead?

**Comment by eloekset** [comment]
Then it must be something else.

**Comment by robinheghan** [comment]
Seems it cannot find the executable. I'm running this on a mac.

```
➜  Migrations DOTNET_CLI_CONTEXT_VERBOSE=true dotnet migrate --provider sqlserver2012 --noConnection -f out.sql
Running /usr/local/share/dotnet/dotnet exec --depsfile /Users/skinney/.nuget/packages/.tools/FluentMigrator.Runner.Cli/1.0.0-beta5/netcoreapp1.0/FluentMigrator.Runner.Cli.deps.json --additionalprobingpath /Users/skinney/.nuget/packages /Users/skinney/.nuget/packages/FluentMigrator.Runner.Cli/1.0.0-beta5/lib/netcoreapp1.0/dotnet-migrate.dll --provider sqlserver2012 --noConnection -f out.sql
Process ID: 28308
Using project '/Users/skinney/Workspace/cop/Migrations'.
Using framework 'net461'.
Running /usr/local/share/dotnet/dotnet build /Users/skinney/Workspace/cop/Migrations/project.json --configuration Debug --framework net461
Process ID: 28309
Project Migrations (.NETFramework,Version=v4.6.1) will be compiled because inputs were modified
    /Users/skinney/Workspace/cop/Migrations/project.json
Compiling Migrations for .NETFramework,Version=v4.6.1
Running /usr/local/share/dotnet/dotnet /usr/local/share/dotnet/sdk/1.0.0-preview2-003131/csc.dll -noconfig @/Users/skinney/Workspace/cop/Migrations/obj/Debug/net461/dotnet-compile-csc.rsp
Process ID: 28310
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.6050881

Using project '/Users/skinney/Workspace/cop/Migrations'.
Using framework 'net461'.
Invoking 'FluentMigrator.Runner.Cli.Executor' for '.NETFramework,Version=v4.6.1'.
Command not found.
```

**Comment by robinheghan** [comment]
Ok. So forking the project and building my own version of the runner that executes ''FluentMigrator.Runner.Cli.Executor.exe' fixes the command not found problem, but it still doesn't seem to trigger any migrations :/

**Comment by eloekset** [comment]
I get the same verbose output ending with "Command not found." on both Windows and Mac if I run **dotnet migrate** in the context of my own test project. 

If I run the following command in the context of this repo's test\TestMigrations folder, it works fine:

```
dotnet ..\..\src\FluentMigrator.Runner.Cli\bin\Debug\netcoreapp1.0\dotnet-migrate.dll --provider sqlserver2012 --connectionString "Server=(localdb)\mssqllocaldb;Database=TestMigrations;Trusted_Connection=True;MultipleActiveResultSets=true" --task migrate --verbose --configuration Debug --outputFile "test.sql"
```

![2016-10-02-14-05-57](https://cloud.githubusercontent.com/assets/791721/19020466/c10524fa-88a9-11e6-907a-edc48376a6f9.png)

So after building a solution with a project structure like the repo, I'm able to run both in Visual Studio and from the command line on Windows:
![2016-10-02_14-46-47](https://cloud.githubusercontent.com/assets/791721/19020643/55b97d08-88af-11e6-8f03-855db5ccabfc.png)

I tried to zip, copy and build the solution on a Mac, but the command line build can't resolve the project reference to the Executor project, so I found that adding a global.json file in the same folder as my .sln file should make project references work outside of Visual Studio, but then I ran into this issue:
![2016-10-02_15-08-54](https://cloud.githubusercontent.com/assets/791721/19020778/7b86b854-88b2-11e6-8302-3482a640d0a2.png)
https://github.com/dotnet/cli/issues/2159

**Comment by giggio** [comment]
I have not tested this in a Mac or Linux, as FluentMigrator is not compatible with .NET Standard, so I would have to have Mono installed. I am sure it works on Windows, I have it running in several projects.
I can't see to repro the problem, if you can be more specific we can then ask someone who works on a Mac to send a PR.

**Comment by eloekset** [comment]
I think it will run on Mono on a Mac if I could get the project reference to work like in VS. I haven't spent any more time trying to find a solution to the "Malformed token" error in my global.json.

@giggio How do you get the command working in your projects? (ref the "Command not found" error) You're not building this repo's projects together with your migrations assembly, but it works for you using the NuGet packages?

.NET Standard support is in the backlog: https://github.com/schambers/fluentmigrator/issues/712
